import pandas as pd

from ..utils.message import print_message
from ..controller.utils.pro_utils import fix_carrers

COLUMNS_NAMES = [
    "PERIODO",
    "COD_SEDE",
    "SEDE",
    "COD_FACULTAD",
    "FACULTAD",
    "COD_UAB",
    "UAB",
    "COD_PROGRAMA",
    "PROGRAMA",
    "COD_PLAN",
    "PLAN",
    "TIPO_NIVEL",
    "COD_NIVEL",
    "NIVEL",
    "COD_SNIES",
    "NOMBRES",
    "APELLIDO1",
    "APELLIDO2",
    "T_DOCUMENTO",
    "DOCUMENTO",
    "HIST_ACADEMICA",
    "CONVOCATORIA",
    "APERTURA",
    "FECHA_NACIMIENTO",
    "CORREO",
    "GENERO",
    "COD_ACCESO",
    "ACCESO",
    "COD_SUBACCESO",
    "SUBACCESO",
    "COD_PLAN_ORIGEN",
    "PLAN_ORIGEN",
    "ESTRATO",
    "PBM",
    "EXTRANJERO",
    "COD_PAIS_NACIMIENTO",
    "PAIS_NACIMIENTO",
    "COD_DEPARTAMENTO_NACIMIENTO",
    "DEPARTAMENTO_NACIMIENTO",
    "COD_MUNICIPIO_NACIMIENTO",
    "MUNICIPIO_NACIMIENTO",
    "COD_DEPTO_RESIDENCIA",
    "DEPTO_RESIDENCIA",
    "COD_MUN_RESIDENCIA",
    "MUN_RESIDENCIA",
    "MATRICULAS",
    "TIPCOLEGIO",
    "COD_COLEGIO",
    "NOMBRE_COLEGIO",
    "ESCOLARIDAD_MADRE",
    "ESCOLARIDAD_PADRE",
    "NUMERO_HIJOS",
    "RESPONSABLE",
    "NUM_HERMANOS",
    "PROPIEDAD_VIVIENDA",
    "COD_NODO_INICIO",
    "NODO_INICIO",
    "PROMEDIO_SEMESTRE",
    "PAPA_SEMESTRE",
    "PERIODO_PROMEDIO",
    "CANCELACION",
    "SNP",
    "PUESTO_ADMISION",
    "PUNTAJE_ESTANDAR_TOTAL",
    "PUNTAJE_TOTAL",
    "COD_SEDE_MOVILIDAD",
    "SEDE_MOVILIDAD",
    "ETAPA_PEAMA"
    ]

def load_enrolled(year: str) -> pd.DataFrame :
    f = pd.read_csv(f'./data/enrolled/enrolled_{year}.csv', header=None, sep=";", names=COLUMNS_NAMES, encoding='utf8', dtype=str)
    f['COD_PLAN'] = fix_carrers(f["COD_PLAN"])
    print_message('ENROLLED READED', f)
    return f